spring.application.name=codingplatform
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=cp
spring.datasource.password=cpdb09
spring.datasource.url=jdbc:postgresql://localhost:5432/cp_db
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect